spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: banana
    password: banana123
    driver-class-name: oracle.jdbc.OracleDriver

mybatis:
  type-aliases-package: com.carrot.market.vo
  mapper-locations: classpath:/mapper/*.xml

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
